version: '3.6'

x-logging:
  &local-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "50"

x-loki-logging:
  &loki-logging
  driver: "loki"
  options:
    max-size: "20m"
    max-file: "50"
    loki-url: "[% loki_url %]"
    loki-external-labels: "container_name={{.Name}},hostname=[% host_name %]"
    loki-pipeline-stages: |
          - multiline:
              firstline: '^\d{4}-\d{2}-\d{2}[T ]?\d{2}:\d{2}:\d{2}.\d{3}'
          - labeldrop:
              - compose_project
              - compose_service
              - filename
              - source
              - stream
              - swarm_service
              - swarm_stack
services:
    certs:
        container_name: oe-certs 
        image: itechuw/certgen:main
        platform: linux/amd64
        restart: always
        environment:
            - KEYSTORE_PW="kspass"
            - TRUSTSTORE_PW="tspass"
        networks:
            - openelis-network
        volumes:
            -  key_trust-store-volume:/etc/openelis-global
            -  keys-vol:/etc/ssl/private/
            -  certs-vol:/etc/ssl/certs/

    db.openelis.org:
        container_name: openelisglobal-database 
        image: itechuw/openelis-global-2-db-bundled:main
        platform: linux/amd64
        ports:
            - "15432:5432"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=clinlims
            - POSTGRES_INITDB_ARGS="--auth-host=md5" 

            - DB_PASSWORD=clinlims
            - DB_SUPERUSER_PASSWORD=superuser
        volumes:
              # preserves the database between containers
            - ./volumes/database/data:/var/lib/postgresql/data                
        logging: *local-logging    
        networks:
            - openelis-network
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
            timeout: 45s
            interval: 10s
            retries: 10 
            
    oe.openelis.org:
        container_name: openelisglobal-webapp 
        image: itechuw/openelis-global-2-bundled:main
        platform: linux/amd64  
        depends_on:
            - db.openelis.org
            - certs
        ports:
            - "8080:8080"
            - "8443:8443"
        restart: always
        networks:
          openelis-network:
              ipv4_address: 172.20.1.121
        logging: *local-logging      
        environment:
            - DEFAULT_PW=adminADMIN! 
            - TZ=America/New_York
              # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://db.openelis.org:5432/clinlims -Ddatasource.username=clinlims -Ddatasource.password=clinlims
            # Remote server Configuration
            # - ORG_OPENELISGLOBAL_REMOTE_SOURCE_URI=http://fhir.openelis.org:8080/fhir/
            # - ORG_OPENELISGLOBAL_REMOTE_SOURCE_UPDATESTATUS=false
            # - ORG_OPENELISGLOBAL_REMOTE_SOURCE_IDENTIFIER=Practitioner/*
            # - ORG_OPENELISGLOBAL_REMOTE_POLL_FREQUENCY=120000
            # - ORG_OPENELISGLOBAL_TASK_USEBASEDON=true
            # SAML Configuration
            # - ORG_ITECH_LOGIN_SAML=true
            # - ORG_ITECH_LOGIN_SAML_REGISTRATIONID=keycloak
            # - ORG_ITECH_LOGIN_SAML_ENTITYID=OpenELIS-Global_saml
            # - ORG_ITECH_LOGIN_SAML_METADATALOCATION=http://keycloak.openelis.org:8080/realms/OpenELIS/protocol/saml/descriptor

        volumes:
            -  key_trust-store-volume:/etc/openelis-global
            -  lucene_index-vol:/var/lib/lucene_index
            
    fhir.openelis.org:
        container_name: external-fhir-api
        image: itechuw/openelis-global-2-fhir:latest
        platform: linux/amd64
        ports:
            - "8081:8080"
        depends_on:
            - db.openelis.org
            - certs    
        networks:
            - openelis-network
        restart: always
        environment:
            # --- MANAGEMENT / ACTUATOR ---
            - management.endpoints.web.exposure.include=health,prometheus

            # --- SPRING CONFIG ---
            - spring.main.allow-circular-references=true
            - spring.flyway.enabled=false
            - spring.flyway.check-location=false
            - spring.flyway.baselineOnMigrate=true

            - spring.datasource.url=jdbc:postgresql://db.openelis.org:5432/clinlims?currentSchema=clinlims
            - spring.datasource.username=clinlims
            - spring.datasource.password=clinlims
            - spring.datasource.driverClassName=org.postgresql.Driver
            - spring.datasource.max-active=15
            - spring.datasource.hikari.maximum-pool-size=10

            - spring.jpa.properties.hibernate.format_sql=false
            - spring.jpa.properties.hibernate.show_sql=false
            - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
            - spring.jpa.properties.hibernate.hbm2ddl.auto=update
            - spring.jpa.properties.hibernate.search.enabled=true

            # --- HAPI FHIR CONFIG ---
            - hapi.fhir.openapi_enabled=true
            - hapi.fhir.fhir_version=R4
            - hapi.fhir.cr_enabled=false
            - hapi.fhir.server_address=http://fhir.openelis.org:8080/fhir/
            - hapi.fhir.allow_external_references=true
            - hapi.fhir.auto_create_placeholder_reference_targets=true
            - hapi.fhir.default_pretty_print=false
            - hapi.fhir.default_page_size=100
            - hapi.fhir.advanced_lucene_indexing=false
            - hapi.fhir.bulk_export_enabled=false
            - hapi.fhir.bulk_import_enabled=false
            - hapi.fhir.fhirpath_interceptor_enabled=false
            - hapi.fhir.narrative_enabled=false
            - hapi.fhir.mdm_enabled=false
            - hapi.fhir.cors.allow_Credentials=true
            - hapi.fhir.cors.allowed_origin=*
            - hapi.fhir.search-coord-core-pool-size=20
            - hapi.fhir.search-coord-max-pool-size=100
            - hapi.fhir.search-coord-queue-capacity=200
            - hapi.fhir.max_page_size=200
            - hapi.fhir.retain_cached_searches_mins=60
            - hapi.fhir.reuse_cached_search_results_millis=1
            - hapi.fhir.inline_resource_storage_below_size=4000
            - hapi.fhir.subscription.resthook_enabled=true

            # --- TESTER CONFIG ---
            - hapi.fhir.tester.home.name="OE adjacent FHIR Store"
            - hapi.fhir.tester.home.server_address=http://fhir.openelis.org:8080/fhir/
            - hapi.fhir.tester.home.refuse_to_fetch_third_party_urls=false
            - hapi.fhir.tester.home.fhir_version=R4

        logging: *local-logging                          

         
    frontend.openelis.org:
        image: itechuw/openelis-global-2-frontend:latest
        container_name: openelisglobal-front-end
        platform: linux/amd64
        networks:
            - openelis-network
        environment:
            - CHOKIDAR_USEPOLLING=true
        logging: *local-logging    
        tty: true

    proxy:
        image: itechuw/openelis-global-2-proxy-bundled:main
        container_name: openelisglobal-proxy
        platform: linux/amd64
        ports:
            - 80:80
            - 443:443
        volumes:
            - certs-vol:/etc/nginx/certs/
            - keys-vol:/etc/nginx/keys/

        restart: unless-stopped
        networks:
            - openelis-network
        logging: *local-logging    
        depends_on:
            - certs              

networks:
  openelis-network:
    name: openelis-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24  
        
volumes:
  db-data:
  key_trust-store-volume:
  certs-vol:
  keys-vol:
  lucene_index-vol:
